Symantec Management Center Connector v1.0.0
fortinet-fortisoar/connector-symantec-management-center pull request #1
Opened 2023-08-07 06:03 UTC by cs-omkar-kumbhar

UTCs:
Connector installation verified.
Connector logo verified.
Actions and Playbook list verified.
Playbook tags verified.
All Playbook are in info mode verified.
All Playbook are in inactive mode verified.

2023-08-07 07:27 UTC, cs-utkarsh-surana requested changes

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/playbooks/playbooks.json
> +                  "output_data": "{{vars.result}}"
Remove it as it causes duplication of data in the data base from all actions

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/operations.py
> +        server_url = config.get("server_url")
strip('/') from the url

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/operations.py
> +            response = request(method, endpoint, headers=headers, auth=(self.username, self.password), params=params, data=json.dumps(data), verify=self.verify_ssl)
Include the curl utils action to make the curl of all the requests.

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/info.json
> +          "tooltip": "Query filter parameter to filter by author.",
change it to name in both tooltip and description.

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/operations.py
> +    return ob.api_request("POST", "/policies", data=params)
can you take /policies as constant as it is used in all actions?

2023-08-07 07:27 UTC, cs-utkarsh-surana commented on symantec-management-center/info.json
> +      "operation": "get_policy_content_by_version",
Please arrange all the actions in the CRUD sequence.

2023-08-09 05:07 UTC, cs-prerna-joshi approved these changes

2023-08-09 05:07 UTC, merged